### ISSUE TITLE
Manifest syntax error

### ISSUE THREAD

**Issue by hitman249** [clastix/kubelived#16]
https://github.com/clastix/kubelived/blob/v0.2.1/charts/kubelived/templates/keepalived-manifest.yaml#L39

**Comment by bsctl** [comment]
@hitman249 thanks for reporting this.

**Comment by bsctl** [comment]
@alegrey91

populate the `resources` with default values coming from the `values.yaml` file

```
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 200m
      memory: 128Mi
```
